version: '3.8'

services:
  server:
    image: videochat-project
    deploy:
      replicas: 1
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: "200m"
        max-file: "10"
    ports:
      - 8070:8070
    command: --addr :8070

